<a href="https://colab.research.google.com/github/rishavk77-bit/Localrepo/blob/main/deeplearning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print("Hello world")

Hello


In [2]:
#Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [5]:
#Vectors or 1d tensor
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [6]:
t2.dtype

torch.float32

In [7]:
# Matrix
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [12]:
lis = [t1,t2,t3,t4]
for t in lis:
  print(t,"\n",t.shape,"\n","\n")

tensor(4.) 
 torch.Size([]) 
 

tensor([1., 2., 3., 4.]) 
 torch.Size([4]) 
 

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) 
 torch.Size([3, 2]) 
 

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]]) 
 torch.Size([2, 2, 3]) 
 



In [14]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b


(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [15]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [16]:
# Compute derivatives
y.backward()

In [17]:
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [21]:
## Create a tensor that has a fixed values for every elements
t6 = torch.full((3,2),42)
print(t6)

tensor([[42, 42],
        [42, 42],
        [42, 42]])


In [24]:
t7 = torch.cat((t3,t6))
print(t7)
print(t7.shape)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])
torch.Size([6, 2])


In [30]:
t8 = torch.sin(t7)
print(t8)
t8.shape

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])


torch.Size([6, 2])

In [34]:
t9 = t8.reshape(3,2,2)
print(t9)
t9.shape

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])


torch.Size([3, 2, 2])

In [35]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [36]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [37]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [38]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])